#!/usr/bin/env bash
# Reads secrets from AWS SSM Parameter Store and writes backend/.env
# Requires: aws cli, EC2 instance role with ssm:GetParameter permission
# Usage: ./load-secrets.sh [SSM_PREFIX]
#   SSM_PREFIX defaults to /ektor-pool-services/prod

set -euo pipefail

SSM_PREFIX="${1:-/ektor-pool-services/prod}"
ENV_FILE="$(dirname "$0")/.env"
REGION="${AWS_DEFAULT_REGION:-us-east-1}"

fetch() {
  aws ssm get-parameter \
    --name "${SSM_PREFIX}/$1" \
    --with-decryption \
    --region "$REGION" \
    --query "Parameter.Value" \
    --output text
}

echo "Loading secrets from SSM prefix: ${SSM_PREFIX}"

cat > "$ENV_FILE" <<EOF
# Generated by load-secrets.sh — do not edit manually
DB_NAME=$(fetch DB_NAME)
DB_USER=$(fetch DB_USER)
DB_PASSWORD=$(fetch DB_PASSWORD)
DB_ROOT_PASSWORD=$(fetch DB_ROOT_PASSWORD)
SECRET_KEY=$(fetch SECRET_KEY)
ANTHROPIC_API_KEY=$(fetch ANTHROPIC_API_KEY)
EOF

chmod 600 "$ENV_FILE"
echo ".env written successfully (${ENV_FILE})"
