apiVersion: v1
kind: Secret
metadata:
  name: pool-api-secrets
type: Opaque
stringData:
  DB_HOST: "db"
  DB_PORT: "3306"
  DB_USER: "pooluser"
  DB_PASSWORD: "poolpass"
  DB_NAME: "pool_services"
  JWT_SECRET_KEY: "local-dev-secret"
